name: project_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  flutter_map: ^6.1.0      # Added for free OpenStreetMap integration
  latlong2: ^0.9.0         # Required for flutter_map coordinates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sportify.jpeg
    - assets/images/gym2.jpeg
    - assets/images/boy_gym.png
    - assets/images/general.jpeg
    - assets/images/welose.jpeg
    - assets/images/plans.jpeg
    - assets/images/sportedu.jpeg
    - assets/images/pstrainer.jpeg
    - assets/images/amen.jpeg
    - assets/images/grams.jpeg
    - assets/images/welcome.jpeg
    - assets/images/welcome2.jpeg
    - assets/images/welcome3.jpeg
    - assets/images/run_jo.jpeg
    - assets/images/yasmmen_pool.jpeg
    - assets/images/Achievements.jpeg
    - assets/images/golds_gym.jpeg
    - assets/gym.jpeg
    # Add these if you're using them in your carousel
